### ISSUE TITLE
Feature Request: OpenRouter.ai Connector Support

### ISSUE THREAD

**Issue by jechaviz** [bootstrapguru/dexor#33]
Implement support for OpenRouter in the Dexor. OpenRouter is an unified interface for LLMs.
It's an unified api to run models in openai, gemini, anthropic and other vendors and opensources models, we can use native api keys bought in our ai provider.

Models supported:
https://openrouter.ai/models

Code sample:
https://github.com/moe-mizrak/laravel-openrouter
https://github.com/moe-mizrak/laravel-prompt-alchemist

**Comment by vijaythecoder** [comment]
Just released the integration for the openrouter.ai Thanks for recommending this.
