### ISSUE TITLE
[Bug Report]:  Dexor Unable to Access or Read Actual Directory Structure

### ISSUE THREAD

**Issue by HamdaanETH** [bootstrapguru/dexor#39]
Description:
I've encountered a critical issue with Dexor (version 1.1) where it's unable to correctly access or read the actual directory structure of my project. Instead of displaying the real files and folders, Dexor consistently reports a fictional directory structure that does not match the actual contents of my project folder.

Steps to Reproduce:
1. Install Dexor using `composer global require bootstrapguru/dexor`
2. Navigate to a project directory
3. Run `dexor`
4. Attempt to list files in the current directory using Dexor

Expected Behavior:
Dexor should accurately list the files and folders in the current directory, matching the output of `ls -la`.

Actual Behavior:
Dexor reports a fictional directory structure that does not exist in the actual project folder.

Actual Directory Structure (from `ls -la`):
LICENSE, README.md, app (directory), bootstrap (directory), box, box.json, 
builds (directory), composer.json, composer.lock, config (directory), 
database (directory), dexor, dexor_config, docs (directory), etc.

Directory Structure Reported by Dexor: made this up with Ai
* app.py
* config.py
* controllers
* models
* routes.py
* tests
* requirements.txt
* setup.py
* __init__.py

Additional Information:
- OS: macOS 13.0.1
- Dexor Version: 1.1
- PHP Version: 8.3.9
- Composer Version: 2.7.7

I've attempted to update Dexor using `composer global update bootstrapguru/dexor`, but the issue persists.

This issue severely limits Dexor's functionality as it cannot interact with the actual project files. Any assistance in resolving this would be greatly appreciated.

**Comment by vijaythecoder** [comment]
can you provide which AI Provider are you using? Also, is it possible to provide the prompt that you are using? 

The expected behavior is in the following video, I am using Deep Seek Coder V2 from Deep Seek from https://deepseek.com/ I suggest using the model with Tool/Function calling, when I test offline models using Ollama, some times they work and some times they don't due to the limited function calling they support. Let me know! 

https://github.com/user-attachments/assets/9ce0dfa5-03d8-4fc0-bcc2-101d2f2ab137

**Comment by HamdaanETH** [comment]
Hey Thank you for your help, seems like something is wrong with ollama, now that I am using claude, it seems to work perfectly. If we can also have ollama work since I use my workstation to serve my open source models that would be great. Either way thank you for your help. Can't wait to test the product

**Comment by vijaythecoder** [comment]
Hey @HamdaanETH,

No worries at all, and I'm really glad to hear it's working well with Claude! 😊

Regarding Ollama, I'm curious about which model you initially tried that didn't work as expected. This will help me in debugging. I've actually had some success with [llama3-groq-tool-use](https://ollama.com/library/llama3-groq-tool-use), although the responses aren't always ideal. But anything with Tool support on ollama should do the job.
